### ISSUE TITLE
View Icon for Passwords when Signing Up + Confirm Password Check

### ISSUE THREAD

**Issue by Sidragon123** [buildingu/Building-u-feedback#36]
## Summary
View toggle to allow users to see or hide the password they enter.

## Problem Statement
Mistyping password when registering leading to redundant password resets or unnecessary new account creation

## Proposed Solution
View Icon toggle and a confirm password input field when signing up

## Additional Context
N.A.

## Acceptance Criteria
- View Icon toggle and a confirm password input field when signing up

## Resources
N.A.

## Dependencies
N.A.

**Comment by devansh-dek** [comment]
Is this issue still open ? Can i work on it?

**Comment by gbudjeakp** [comment]
@devansh-dek  Sorry for the late response. Yes feel free to fork and work on it

**Comment by Cheemma1** [comment]
@gbudjeakp I have worked on this issue.
