### ISSUE TITLE
Cannot sign up

### ISSUE THREAD

**Issue by AndyX07** [buildingu/Building-u-feedback#44]
**Describe the bug**
When you fill in the form in https://buildingu.github.io/Building-u-feedback/signup, the signup button doesn't work when clicked.

**To Reproduce**
1. Go to https://buildingu.github.io/Building-u-feedback/signup
2. Fill out form
3. Click sign up

**Expected behavior**
Expected to be redirected to new page with account.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by gbudjeakp** [comment]
This is related to this issue https://github.com/buildingu/Building-u-feedback/issues/42 and I'm looking into it

**Comment by gbudjeakp** [comment]
Issue has been resolved. Used a new hosting solution.l
