### ISSUE TITLE
Documentation for setting up database locally using docker

### ISSUE THREAD

**Issue by gbudjeakp** [buildingu/Building-u-feedback#49]
## Summary
We currently have just one way of setting up a database locally for development. 
we need another way for people who cannot download xammp or can't use it or just don't want it.

## Problem Statement
Would create more options for developers to choose what local database setup they want. 

## Acceptance Criteria

- [ ] Instruction in the README page on how to setup a database locally using docker

**Comment by Shravanth007** [comment]
Hey There i would like make the documentation for setting up docker

**Comment by CodingWithError** [comment]
can you assign me this issue

**Comment by Shravanth007** [comment]
Should i add the setup Documentation of the docker in the available readme? 
Can you assign me this issue?

**Comment by gbudjeakp** [comment]
@CodingWithError I'll assign this to you. It'll be in the readme under the "setting up database" section

**Comment by Shravanth007** [comment]
Check it if you want any changes that can be made.
