### ISSUE TITLE
UI improvement on sign up page.

### ISSUE THREAD

**Issue by crazyshrut** [buildingu/Building-u-feedback#60]
## Summary
Instead of cap case it should be small case to increase the readability.

## Problem Statement
Right now, every word's first letter is caps, and because of it readability is missing.

## For reference:

It can be => Already have an account?

![Screenshot from 2024-08-17 14-58-12](https://github.com/user-attachments/assets/6f769d32-daf0-42ec-a726-7ab54beafb8b)

**Comment by crazyshrut** [comment]
hey @gbudjeakp , can you assign it to me?
I want to work on it.

**Comment by gbudjeakp** [comment]
Sound good. Great Catch

**Comment by crazyshrut** [comment]
Thanks @gbudjeakp, I will raise the PR by tonight.
